name: Build and Release

on:
  push:
    branches:
      - master
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build exe
      run: |
        pyinstaller --onefile --name PackNMove file_compressor.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PackNMove
        path: dist/PackNMove.exe

  release:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: PackNMove
        path: ./

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/PackNMove.exe
